### ISSUE TITLE
Problem with the USB camera

### ISSUE THREAD

**Issue by lebearnais64** [fran6p/OPiz2#1]
Thanks a lot for your scripts. It works ver well
My only issue is about the UBS cam. When the installation is done, the oranpi zero 2 reboot.
I see my webcam which is on. I have the screens to configure test name, .... and the printer. I can see my video on the dashboard. When I restart the orangepi 2, it restart but the webcam is not working anymore.
Do you have some answer?

RegardS.

**Comment by fran6p** [comment]
Hi,
I currently no more use OrangePi Zero2 with my 3D printers as I had some issues and the Webcam is one of them.
I'll have to investigate but as I see it, I think the problem is on the device the Webcam is assignated. The script webcamDaemon use /dev/video0 and if the Webcam for any reason isn't on this device it won't work :-( 
You could try to append " -d /dev/video1" to «MJPGSTREAMER_INPUT_USB="input_uvc.so"»
=> «MJPGSTREAMER_INPUT_USB="input_uvc.so -d /dev/video1"»
and modify the line «if [ -e "/dev/video0" ] && { [ "\$camera" = "auto" ] || [ "\$camera" = "usb" ] ; }; then»
as «if [ -e "/dev/video1" ] && { [ "\$camera" = "auto" ] || [ "\$camera" = "usb" ] ; }; then»
Save the file webcamDaemon and reboot to test if it works.
Sinon je pense que tu maitrises la langue française et je t'invite à poser ton problmèe sur le forum lesimprimantes3d.fr
Best regards

**Comment by lebearnais64** [comment]
Merci pour ta réponse rapide et clair.

Peux tu  me dire quelle carte tu utilises maintenant avec tes imprimantes
3D?
J'étais avec des raspberry pi mais introuvable maintenant.

Je vais essayer ce que tu m'as dit.

bonne journée.

**Comment by fran6p** [comment]
Au niveau des  cartes, j'utilise principalement des Raspberry Pi (j'ai un stock constitué au fil des années allant du premier RPi au RPi4 (1,2 et 4 Go) en passant par des Zero et Zero2 ainsi que quelques CM4), sinon je teste actuellement la carte CB1 de Bigtreetech avec son adaptateur Pi4B qui fonctionne mais possède quelques limitations (pas de prise en charge des connecteurs CSI / DSI (camera / écran)) et quelques bugs (Wifi erratiques et/ou Ethernet absent en fonction du kernel de l'OS installé).
Sinon, j'ai rallumé la OPiz2 et changé uniquement la ligne des options MJPGSTREAMER_INPUT_USB="input_uvc.so -d /dev/video1" en ajoutant le périphérique sur lequel la Webcam se connecte, redémarré et Bingo, la caméra est réapparue.
Plusieurs reboot plus tard, elle est toujours visible.
Je vais donc clore ce «bug».
